server:
  port: 7070
spring:
  application:
    name: ahcc-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/jorgecahui/xan.git # ruta del repositorio git
          searchPaths: ahcc-config-data
          default-label: main
  security:
    user:
      name: root
      password: 1234567